### ISSUE TITLE
Generated config sometimes unusable

### ISSUE THREAD

**Issue by jvstein** [rbtr/pachinko#6]
The config generated by `pachinko config` is not always usable. This is because the order of the `processors` list is non-deterministic and potentially reordered each time it is written.

The particular issue I ran into is that the `video-id` processor must be executed before the `tv-id` processor (because of the check in [video.go#L42](https://github.com/rbtr/pachinko/blob/master/plugin/processor/vidid/video.go#L42). If the processors are out of order, it will not work.

Example bad config created by the command:

```
dry-run: false
inputs:
- name: path
  src-dir: ./src
log-format: text
log-level: info
outputs:
- create-dirs: true
  dry-run: true
  name: move
  overwrite: false
- name: stdout
pipeline:
  buffer: 0
processors:
- api-key: ""
  name: tvdb
  request-limit: 10
- dest-dir: dest
  episode-names: false
  format: not-implemented
  name: tv-dest
  season-dirs: true
  tv-prefix: tv
- matchers:
  - (?i)(?:s+\d+)(?:\.|\s|-|_|x)*(e+\d+)
  - (?i)(?:season)+(?:(?:\.|\s|-|_|x|\/)\d+)
  - (?i)(?:[^[:alpha:]\d])\d{1,3}[x-]\d{1,3}
  name: tv-id
- matchers:
  - (?i)\b([\s\w.-]*)[\s.\/-]+(?:\((\d+)\))?[\s.\/-]?(\d{1,3})[x-](\d{1,3})
  - (?i)\b([\s\w.-]*?)?(?:[\s\(.\/-](\d{4})[\s\).\/-])?[\s\w.-]?(?:s+(\d+))(?:\.|\s|-|_|x)*(?:e+(\d+))
  - (?i)\b([\s\w.-]*)[\s.\/-]+(?:\((\d+)\))?[\s.\/-]?(?:season|series).?(\d+).?(?:episode)?[^\d(]?(\d+)
  name: tv-meta
  sanitize-name: true
- file-types:
  - .avi
  - .divx
  - .m4v
  - .mkv
  - .mov
  - .mp4
  - .xvid
  name: video-id
```
